# Generated by Django 5.2.2 on 2025-06-22 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='blog_posts',
        ),
    ]
